### ISSUE TITLE
doesn't work in dash shell

### ISSUE THREAD

**Issue by andreyorst** [JJK96/kakoune-rainbow#1]
when I call `:rainbow` I see this error in `*debug*` buffer:
```
shell stderr: <<<
/usr/bin/dash: 4: /usr/bin/dash: Syntax error: "(" unexpected
>>>
```

**Comment by JJK96** [comment]
The following line is the cause of the error.
https://github.com/JJK96/kakoune-rainbow/blob/2188d144631d3c72b80e6ed36ae788f78fb7ea9d/rainbow.kak#L26
Posix does not have arrays other than $@. 
I have been looking at indexing $@ with a variable, but haven't found it yet.

**Comment by andreyorst** [comment]
I've done arrays in dash by using generators:
![image](https://user-images.githubusercontent.com/19470159/70628886-083b3400-1c3a-11ea-8b16-d1ed0ce68937.png)
Basically we generate variables with names containing index of array. If wrapped into functions like push and pop this can serve well. Another more complex example of multidimenisonal arrays:

![image](https://user-images.githubusercontent.com/19470159/70628675-a2e74300-1c39-11ea-9ef6-f41ae5dd29cd.png)
(sorry screenshot is the only thing I have)

Perhaps something like this could be used instead of arrays from bash?

**Comment by JJK96** [comment]
I pushed an attempt to fix this

**Comment by andreyorst** [comment]
it works now, but It seems sometimes it colors parens wrong way:

![image](https://user-images.githubusercontent.com/19470159/70630346-7aad1380-1c3c-11ea-8b7a-3cbc8e4cc658.png)

**Comment by JJK96** [comment]
I think that is another issue? Or is there any reason to think this is related to dash?

EDIT: Also 6dd8f5b might fix this

**Comment by JJK96** [comment]
> it works now, but It seems sometimes it colors parens wrong way:
> 
> ![image](https://user-images.githubusercontent.com/19470159/70630346-7aad1380-1c3c-11ea-8b7a-3cbc8e4cc658.png)

Feel free to open a new issue if this is not fixed
