### ISSUE TITLE
deletion or insertion inside parentheses breaks highlighting

### ISSUE THREAD

**Issue by andreyorst** [JJK96/kakoune-rainbow#2]
![image](https://user-images.githubusercontent.com/19470159/70628418-2d7b7280-1c39-11ea-86fc-8b26b4fc2f48.png)
I've pressed `d`:
![image](https://user-images.githubusercontent.com/19470159/70628436-3409ea00-1c39-11ea-908e-5f57e98f792c.png)

![image](https://user-images.githubusercontent.com/19470159/70628488-513eb880-1c39-11ea-8155-a87335076f06.png)
I've pressed `i1`:
![image](https://user-images.githubusercontent.com/19470159/70628544-63b8f200-1c39-11ea-8bb9-33b6c31bc647.png)

**Comment by JJK96** [comment]
That's because highlighting is not updated.
You could add 
```
hook window InsertIdle .* %{ rainbow }
```

**Comment by andreyorst** [comment]
sure, although that makes it painfully slow on a ~1000 lines file, as I've mentioned here https://discuss.kakoune.com/t/idea-highlight-all-pairs-rainbow/811/9?u=andreyorst

**Comment by JJK96** [comment]
That was also my experience, that's why I didn't include `:rainbow-enable` initially.

For my own usecase highlighting on-demand is good enough.

**Comment by andreyorst** [comment]
Understood, closing then. Although it may be nice to have some functions that enable and disable such hooks

**Comment by JJK96** [comment]
Those functions have been added
